# -*- coding: utf-8 -*-
"""SGT-Analyser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L8pT-EDWfVpq8gYxtq4iRta3kuP5dCoo
"""

from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes.\n'.format(name=fn, length=len(uploaded[fn])))

board_count = int(input('Enter the number of checkerboards at your Well-Plate: '))
print('\n')
first_wells_input = input('Enter the first well of each checkerboard (separated by comma): ')
print('\n')
last_wells_input = input('Enter the last well of each checkerboard (separated by comma): ')
print('\n')
log_time = int(input("Enter time (in [min]) that the investigated bacteria needs to grow one log-level (e.g.: 70): "))
print('\n')
antibiotic_one_name_input = input("Enter the name of the first antibiotic (rising in rows, e.g.: Nitroxolin): ")
print('\n')
antibiotic_two_name_input = input("Enter the name of the second antibiotic (rising in columns, e.g.: Dalbavancin): ")
print('\n')
antibiotic_one_input = input("Enter the concentrations of the first antibiotic (rising in rows), in ascending order and separated by commas (e.g.: Nitroxolin, 0, 8, 32, 64): ")
print('\n')
antibiotic_two_input = input("Enter the concentrations of the second antibiotic (rising in columns), in ascending order and separated by commas (e.g.: Dalbavancin, 0, 8, 32, 64): ")

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/DataSpott/SGT-Analysis.git
# %cd SGT-Analysis/
!python SGT.py board_count log_time antibiotic_one_name_input antibiotic_two_name_input antibiotic_one_input antibiotic_two_input uploaded[0]